config/routes.rb
Rails.application.routes.draw do
  resources :universes
  resources :catalogs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :moons
  resources :entries
  root 'toolbox#landing'
  resources :users
  resources :moons
  get '/dashboard' => 'toolbox#dashboard'
  get '/user_index' => 'toolbox#user_index'
  get '/search' => 'toolbox#search'
  get '/regions' => 'toolbox#regions'
  get '/systems' => 'toolbox#systems'
  get '/user_catalog' => 'toolbox#user_catalog'
  get '/user_dashboard' => 'toolbox#user_dashboard'

  get '/flagged' => 'toolbox#flagged'
  get '/info' => 'toolbox#info'

  get '/' => 'toolbox#landing'



end

app/models/entry.rb
class Entry < ActiveRecord::Base
	 validates :content, :presence => true

	def self.format_check (content, id, user)
		Rails.logger.info "Format Verfication Check"
		formatted_content = content.split("\n")
		formatted_content.each_with_index do |target, i|
			valid = true
				if target.first == "\t"
					scan_results = target.gsub(/\r/,"").split("\t")
					Rails.logger.info "Material check: " + scan_results.to_s
					if scan_results[0] != "" || scan_results[2].to_i > 1 || scan_results[3].length != 5 || scan_results[4].length != 8 || scan_results[5].length != 8 || scan_results[6].length != 8
						valid = false
					end
				else
					valid = false
				end
			Rails.logger.info "Create Moon Entry:" + id.to_s + " | " +  valid.to_s
			if valid == true
				Moon.create :user_id => user.to_i, :entry_id => id.to_i, :product => scan_results[1], :quantity => scan_results[2].to_f, :ore_type_id => scan_results[3].to_i, :system_id => scan_results[4].to_i, :planet_id => scan_results[5].to_i, :moon_id => scan_results[6]
			end
		end
	end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :admin_check, only: [:index, :show, :edit, :destroy, :update]
  before_action :blacklist_check, only: [:new, :create, :edit, :destroy, :update]


  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all.paginate(:page => params[:page], :per_page => 75).order(id: :desc)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    # check = Entry.format_check(@entry[:content])
    @user = User.find(@entry.user)
    @report = Catalog.paginate(:page => params[:page], :per_page => 75).where('entry_id' => params[:id]).order(id: :asc)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
      @entry = Entry.new(entry_params)
      respond_to do |format|
        if @entry.save
          format.html { redirect_to new_entry_path, notice: 'System Log was Created!' }
          format.json { render :show, status: :created, location: @entry }
          Entry.format_check(entry_params[:content], @entry.id, entry_params[:user])
        else
          format.html { render :new }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:content, :user)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user, value: current_user.id  %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, cols: "100", rows: "10" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Entrie Index</h1>
<%= will_paginate @entries, class: "float-left" %>

<table>
  <thead>
    <tr>
      <th>ID|</th>
      <th>User|</th>
      <th>Format_check|</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.id %></td>
        <td><%= entry.user %></td>
        <td><%= entry.format_check %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/entries/new.html.erb
<h1>VRTEX Moon Catalog</h1>

<div>
	<p>
		This tool is designed to parse the new "Copy to Clipboard" feature that was deploied in the EvE online Expansion Lifeblood.  Simply paste the data from your clipboard into the field and send it off for cataloging.  
	</p>
	<p>
		Currently this parser is a 3 step process
		<ol>
			<li>1) Data is checked for validity by a simple string check, to make sure you acutally put the correct data in the form.</li>
			<li>2) Data is checked with ESI and each entry is then flagged as valid if all checks come back true.</li>
			<li>3) Data re-written in a final format and will be avalable for search in the catalog to authorized parties.</li>
		</ol>
		Please note that this site is a work in progress and any errors or issues you have can be reported to the in-game character Bahnd Rollard.
	</p>
</div>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @entry.id  %>
  <strong>User:</strong>
  <%= @user.email %>
</p>

<!--
 <p>
  <strong>Content:</strong>
  <%= @entry.content  %>
</p>
 -->
<%= will_paginate @report, class: "float-left" %>

 <table>
  <thead>
    <tr>
   	  <th>ID</th>
      <th>User</th>
      <th>Entry</th>
      <th>System</th>
      <th>System esi</th>
      <th>Planet</th>
      <th>Planet esi</th>
      <th>Moon</th>
      <th>Moon esi</th>
      <th>Product</th>
      <th>Product</th>
      <th>Percent</th>
      <th>Status</th>
      <th>Verified</th>
      <th>Flag</th>
    </tr>
  </thead>

  <tbody>
    <% @report.each do |catalog| %>
      <tr>
        <td><%= catalog.id %></td>
        <td><%= catalog.user_id %></td>
        <td><%= catalog.entry_id %></td>
        <td><%= catalog.system_id %></td>
        <td><%= catalog.system_esi %></td>
        <td><%= catalog.planet_id %></td>
        <td><%= catalog.planet_esi %></td>
        <td><%= catalog.moon_id %></td>
        <td><%= catalog.moon_esi %></td>
        <td><%= catalog.product_id %></td>
        <td><%= catalog.product %></td>
        <td><%= catalog.percent %></td>
        <td><%= catalog.status %></td>
        <td><%= catalog.verified %></td>
        <td><%= catalog.flag %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- 
<p>
  <strong>Format Check</strong>
  <%= @entry.format_check %>
</p>
 -->

<%= link_to 'Edit', edit_entry_path(@entry) %> |