config/routes.rb
Rails.application.routes.draw do
  resources :universes
  resources :catalogs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :moons
  resources :entries
  root 'toolbox#landing'
  resources :users
  resources :moons
  get '/dashboard' => 'toolbox#dashboard'
  get '/user_index' => 'toolbox#user_index'
  get '/search' => 'toolbox#search'
  get '/regions' => 'toolbox#regions'
  get '/systems' => 'toolbox#systems'
  get '/user_catalog' => 'toolbox#user_catalog'
  get '/user_dashboard' => 'toolbox#user_dashboard'

  get '/flagged' => 'toolbox#flagged'
  get '/info' => 'toolbox#info'

  get '/' => 'toolbox#landing'



end

app/models/toolbox.rb
class Toolbox < ActiveRecord::Base

	def self.resolve_flagged (id)
			Rails.logger.info 'Resolved Flagged Post: ' +  id.to_s
			valid_entry = Catalog.find(id)
			valid_entry.update(flag: nil, status: 4)
			valid_entry.product
			results = Catalog.where('moon_id' => valid_entry.moon_id, 'product' => valid_entry.product)
			results.each do |r|
				if r.id != valid_entry.id 
					Rails.logger.info 'Deleted Post: ' +  r.id.to_s
					Catalog.destroy(r.id)
				end
			end
	end

	def self.EvE_Request (url, id)
		require 'net/http'
		require 'net/https'
		Rails.logger.info "EvE ESI check: " + url.to_s + " | " + id.to_s


			if id != nil
			url = url.gsub(/id/,id)
			end
		uri = URI.parse(url)
		request = Net::HTTP::Get.new(uri)
		request["Accept"] = "application/json"
		req_options = {
			use_ssl: uri.scheme == "https",
		}
		response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
			http.request(request)
		end
		return ActiveSupport::JSON.decode(response.body)

	end

	def self.EvE_Market (item_id)
		Rails.logger.info "EvE ESI Market Lookup: " + item_id.to_s
		# Rails.logger.info "Timestamp: " + Time.now.to_s + " | " + (Time.now-300).to_s  + " | " + $Timestamp.to_s
		$Timestamp = $Timestamp || nil
		if $Timestamp == nil || $Timestamp < Time.now-300
			Rails.logger.info "** Market Data Refresh **"
			$Market_Data = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/markets/prices/?datasource=tranquility', nil)
			$Timestamp = Time.now
		end 

		Rails.logger.info "Market Data: " + $Market_Data.length.to_s
		$Market_Data.each do |i|
			# Rails.logger.info i.to_s
			if i["type_id"] == item_id
				return i["adjusted_price"].to_f
			end
		end
		return nil
	end

	def self.material_check (data)
		# Rails.logger.info "Material Check: " + data.to_s
		if data.to_s.include?("Mercoxit")  || data.to_s.include?("Arkonor") || data.to_s.include?("Bistot") || data.to_s.include?("Crokite") || data.to_s.include?("Gneiss") || data.to_s.include?("Spodumain") || data.to_s.include?("Ochre")  || data.to_s.include?("Hemorphite") || data.to_s.include?("Hedbergite") || data.to_s.include?("Jaspet") || data.to_s.include?("Kernite") || data.to_s.include?("Omber") || data.to_s.include?("Plagioclase") || data.to_s.include?("Pyroxeres") || data.to_s.include?("Scordite") || data.to_s.include?("Veldspar")
			# Rails.logger.info "Material Check: Rock"
			return 'material_rock'
		end
		if data.to_s.include?("Bitumens") || data.to_s.include?("Coesite") || data.to_s.include?("Sylvite") || data.to_s.include?("Zeolites")
			return 'material_R4'
		end
		if data.to_s.include?("Cobaltite") || data.to_s.include?("Euxenite") || data.to_s.include?("Scheelite") || data.to_s.include?("Titanite")
			return 'material_R8'
		end
		if data.to_s.include?("Chromite") || data.to_s.include?("Otavite") || data.to_s.include?("Sperrylite") || data.to_s.include?("Vanadinite")
			return 'material_R16'
		end
		if data.to_s.include?("Zircon") || data.to_s.include?("Pollucite") || data.to_s.include?("Cinnabar") || data.to_s.include?("Carnotite")
			return 'material_R32'
		end
		if data.to_s.include?("Monazite") || data.to_s.include?("Loparite") || data.to_s.include?("Ytterbite") || data.to_s.include?("Xenotime")
			return 'material_R64'
		end
	end
	def self.material_color_check (data)
		# Rails.logger.info "Material Check: " + data.to_s
		if data.to_s.include?("Mercoxit")  || data.to_s.include?("Arkonor") || data.to_s.include?("Bistot") || data.to_s.include?("Crokite") || data.to_s.include?("Gneiss") || data.to_s.include?("Spodumain") || data.to_s.include?("Ochre")  || data.to_s.include?("Hemorphite") || data.to_s.include?("Hedbergite") || data.to_s.include?("Jaspet") || data.to_s.include?("Kernite") || data.to_s.include?("Omber") || data.to_s.include?("Plagioclase") || data.to_s.include?("Pyroxeres") || data.to_s.include?("Scordite") || data.to_s.include?("Veldspar")
			# Rails.logger.info "Material Check: Rock"
			return '#D3D3D3'
		end
		if data.to_s.include?("Bitumens") || data.to_s.include?("Coesite") || data.to_s.include?("Sylvite") || data.to_s.include?("Zeolites")
			return '#778899'
		end
		if data.to_s.include?("Cobaltite") || data.to_s.include?("Euxenite") || data.to_s.include?("Scheelite") || data.to_s.include?("Titanite")
			return 'green'
		end
		if data.to_s.include?("Chromite") || data.to_s.include?("Otavite") || data.to_s.include?("Sperrylite") || data.to_s.include?("Vanadinite")
			return '#0000FF'
		end
		if data.to_s.include?("Zircon") || data.to_s.include?("Pollucite") || data.to_s.include?("Cinnabar") || data.to_s.include?("Carnotite")
			return '#800080'
		end
		if data.to_s.include?("Monazite") || data.to_s.include?("Loparite") || data.to_s.include?("Ytterbite") || data.to_s.include?("Xenotime")
			return '#FFA500'
		end
	end


	def self.repro_breakdown (data)
		repro_data = []
		Rails.logger.info "Repro breakdown"
		data.each do |material|
			Rails.logger.info "Repro: " + material.product.to_s
			case material.product
			when 'Loparite'
				repro_data.push('Promethium', 'Platinum', 'Scandium', 'Hydrocarbons', 'Nocxium', 'Zydrine', 'Megacyte')
			when 'Monazite'
				repro_data.push('Neodinium', 'Chromium', 'Tungsten', 'Evaporite Deposits', 'Nocxium', 'Zydrine', 'Megacyte')
			when 'Xenotime'
				repro_data.push('Dysprosium', 'Vanadium', 'Cobalt', 'Atmospheric Gases', 'Nocxium', 'Zydrine', 'Megacyte')
			when 'Ytterbite'
				repro_data.push('Thulium', 'Cadmium ', 'Titanium', 'Silicates', 'Nocxium', 'Zydrine', 'Megacyte')

			when 'Zircon'
				repro_data.push('Hafnium', 'Titanium', 'Silicates', 'Mexallon', 'Isogen', 'Megacyte')
			when 'Pollucite'
				repro_data.push('Caesium', 'Scandium', 'Hydrocarbons', 'Mexallon', 'Isogen', 'Zydrine')
			when 'Cinnabar'
				repro_data.push('Mercury', 'Tungsten', 'Evaporite Deposits', 'Mexallon', 'Isogen', 'Megacyte')
			when 'Carnotite'
				repro_data.push('Technetium', 'Cobalt', 'Atmospheric Gases', 'Silicates', 'Mexallon', 'Isogen', 'Zydrine')

			when 'Chromite'
				repro_data.push('Chromium', 'Hydrocarbons', 'Pyerite', 'Mexallon', 'Isogen', 'Nocxium')
			when 'Otavite'
				repro_data.push('Cadmium', 'Atmospheric Gases', 'Tritanium', 'Mexallon', 'Isogen', 'Nocxium')
			when 'Sperrylite'
				repro_data.push('Platinum', 'Evaporite Deposits', 'Tritanium', 'Mexallon', 'Isogen', 'Zydrine')
			when 'Vanadinite'
				repro_data.push('Vanadium', 'Silicates', 'Pyerite', 'Mexallon', 'Isogen', 'Zydrine')

			when 'Cobaltite'
				repro_data.push('Cobalt', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Euxenite'
				repro_data.push('Scandium', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Scheelite'
				repro_data.push('Tungsten', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Titanite'
				repro_data.push('Titanium', 'Tritanium', 'Pyerite', 'Mexallon')			

			when 'Bitumens'
				repro_data.push('Hydrocarbons', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Coesite'
				repro_data.push('Silicates', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Sylvite'
				repro_data.push('Evaporite Deposits', 'Tritanium', 'Pyerite', 'Mexallon')
			when 'Zeolites'
				repro_data.push('Atmospheric Gases', 'Tritanium', 'Pyerite', 'Mexallon')		

			end
		end
		return repro_data
	end

	def self.universe_update 
		Rails.logger.info ' + Universe Update + '
		Universe.destroy_all
		@regions = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/regions/?datasource=tranquility', nil)
		@regions.each do |region|
			Rails.logger.info "Region Look up" + region.to_s
			@region_details = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/regions/id/?datasource=tranquility&language=en-us', region.to_s)
			# Rails.logger.info "Const Look up" + @region_details['constellations'].to_s

			if @region_details['name'].to_s.scan(/\d/).empty? == true
				
				@region_details['constellations'].each do |const|
					# Rails.logger.info "const Look up: " + const.to_s
					@const_details = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/constellations/id/?datasource=tranquility&language=en-us', const.to_s)
					@const_details['systems'].each do |system|
						@system_details = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/systems/id/?datasource=tranquility&language=en-us', system.to_s)
						Rails.logger.info "Create Entry: " + @region_details['name'].to_s + " | " + @const_details['name'].to_s + " | " + @system_details['name'].to_s
						universe_entry = Universe.new do |u|
							u.region_id = @region_details['region_id'].to_i
							u.region_name = @region_details['name'].to_s
							u.constellation_id = @const_details['constellation_id'].to_s
							u.constellation_name = @const_details['name'].to_s
							u.system_id = @system_details['system_id'].to_s
							u.system_name = @system_details['name'].to_s
						end
					universe_entry.save
					end
				end

			else
				Rails.logger.info ' + J-space Region (skipping for catalog) + '
			end

		end
	end

end

app/controllers/toolbox_controller.rb
class ToolboxController < ApplicationController
	before_filter :authenticate_user!, only: [:dashboard, :user_index, :catalog, :search, :user_catalog, :regions]
	before_action :admin_check, only: [:user_index, :dashboard, :user_dashboard, :flagged]
	before_action :approval_check, only: [:search, :systems, :regions]

	def landing
		
	end
	def user_dashboard
		@user = User.paginate(:page => params[:page], :per_page => 50).order(id: :desc)
	end
	def info
		@catalogs = Catalog.where('moon_id' => params[:search])
		@material_list = @catalogs.distinct.pluck(:product_id)
		@mats_breakdown = Catalog.where('moon_id' => params[:search]).limit(@material_list.length)
		@chart_array = [[],[],[]]

		@repro_breakdown = Toolbox.repro_breakdown(@mats_breakdown).uniq
		Rails.logger.info "repro_list: " + @repro_breakdown.to_s

	end
	def flagged
		@catalogs = Catalog.paginate(:page => params[:page], :per_page => 75).where.not('flag' => nil).order(moon_esi: :asc, product: :asc, percent: :asc)
		@previous_entry = nil

		if params[:flagged_post] != nil and current_user.admin == true
			Toolbox.resolve_flagged(params[:flagged_post])
			redirect_to flagged_path
		end
	end
	def user_catalog
		@results = Catalog.paginate(:page => params[:page], :per_page => 75).where('user_id' => current_user).where.not('status' => nil || 3).order(moon_esi: :desc)
		@entry_results = @results.map(&:entry_id).uniq
		@mapped_results = @results.map(&:moon_id).uniq

		@material_results = Catalog.paginate(:page => params[:page], :per_page => 75).where('user_id' => current_user).where.not('status' => nil || 3).order(moon_esi: :desc).map(&:product).uniq
			@material_array = [[],[],[],[],[],[]]
			@material_results.each_with_index do |material, i|
			check = Toolbox.material_check(material)
				if check == 'material_R64'
					@material_array[5].push(material)
				elsif check == 'material_R32'
					@material_array[4].push(material)
				elsif check == 'material_R16'
					@material_array[3].push(material)
				elsif check == 'material_R8'
					@material_array[2].push(material)
				elsif check == 'material_R4'
					@material_array[1].push(material)
				elsif check == 'material_rock'
					@material_array[0].push(material)
				end
				Rails.logger.info 'Material Check: ' + check.to_s + " | " + material.to_s + " | " + i.to_s

			end

	end
	def dashboard
		@universe_size = Universe.all.size
		@catalog_size = Catalog.all.size
		@moons_size = Moon.all.size
		@entry_size = Entry.all.size
		@users_size = User.all.size

		if params[:moon_parse] == 'true' and current_user.admin == true
			Moon.Moon_Parse
			redirect_to dashboard_path
		end

		if params[:catalog_parse] == 'true' and current_user.admin == true
			Catalog.catalog_parse
			redirect_to dashboard_path
		end

		if params[:universe_update] == 'true' and current_user.admin == true
			Toolbox.universe_update

			redirect_to dashboard_path
		end

		if params[:flag_count_reset] == 'true' and current_user.admin == true
		 	@user = User.all
		 	@user.each do |i|
		 		i.update(flags: 0)
		 	end
		end
	end
	def user_index
		@user = User.paginate(:page => params[:page], :per_page => 50).order(id: :desc)
	end
	def catalog
		
	end
	def search
		if params[:search].to_s == ''
			redirect_to regions_path
			return
		end

		if params[:search] != nil
		# if params[:search] != nil && params[:region] == nil
			Rails.logger.info 'Search Check: ' +  params[:search].to_s
			# Check params for ID #
			if params[:search].to_s.scan(/\D/).empty? == true
				Rails.logger.info 'Redirect to Info Page: ' +  params[:search].to_s
				redirect_to info_path(search: params[:search])
				return
			end

			# Wildcard Search
			# @results = Catalog.where("system_esi LIKE ?", "%#{params[:search]}%").where.not('status' => nil)

			@results = Catalog.paginate(:page => params[:page], :per_page => 75).where("system_esi LIKE ?", "#{params[:search]}").where.not('status' => nil || 3).order(moon_esi: :desc)
			@entry_results = @results.map(&:entry_id).uniq
			@mapped_results = @results.map(&:moon_id).uniq

			@material_results = Catalog.where("system_esi LIKE ?", "#{params[:search]}").where.not('status' => nil || 3).order(moon_esi: :desc).map(&:product).uniq
			@material_array = [[],[],[],[],[],[]]
			@material_results.each_with_index do |material, i|
				check = Toolbox.material_check(material)
				if check == 'material_R64'
					@material_array[5].push(material)
				elsif check == 'material_R32'
					@material_array[4].push(material)
				elsif check == 'material_R16'
					@material_array[3].push(material)
				elsif check == 'material_R8'
					@material_array[2].push(material)
				elsif check == 'material_R4'
					@material_array[1].push(material)
				elsif check == 'material_rock'
					@material_array[0].push(material)
				end
				Rails.logger.info 'Material Check: ' + check.to_s + " | " + material.to_s + " | " + i.to_s

			end
		# else
		# 	Rails.logger.info 'Region Check'
		# 	# @region_list = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/regions/?datasource=singularity', nil)
		# 	@list = []
		# 	# @region_list.each do |i|
		# 	# 	item = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/regions/id/?datasource=singularity&language=en-us', i.to_s)
		# 	# 	@list.push(item)
		# 	# end
		end

	end
	def regions
		# @test = 'Local Regions'
	end
	def systems

		@systems = Universe.where('region_id' => params[:region]).order(system_name: :asc)

		# @region_list = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/regions/id/?datasource=singularity&language=en-us', params[:region])
		# Rails.logger.info @region_list.to_s
		# @region_list["constellations"].each do |i|


		# 	item = Toolbox.EvE_Request('https://esi.tech.ccp.is/latest/universe/constellations/id/?datasource=singularity&language=en-us', i.to_s)
		# 	Rails.logger.info item

		# 	# @system_list.push(item)
		# end
	end
end

app/views/toolbox/catalog.html.erb
<h1>Catalog page</h1>
<p>
Work in Progress
</p>
<p>
Valadation step 2 of 3
</p>

app/views/toolbox/dashboard.html.erb
<h3>Dashboard</h3>
<p><%= link_to 'User Index', user_index_path, class: "btn btn-default", id: ""  %> <strong>User Count:</strong> <%= @users_size %></p>

<p><%= link_to 'Entry Index', entries_path, class: "btn btn-default", id: ""  %> <strong>Entry Count: </strong><%= @entry_size %></p>

<p>
	<%= link_to 'Moon Index', moons_path, class: "btn btn-default", id: ""  %>
	<%= link_to "Moon Parse", {:controller => "toolbox", :action => "dashboard", :moon_parse => true }, class: "btn btn-warning", id: "" %>
	<strong>Moons Size:</strong> <%= @moons_size %>
</p>

<p>
	<%= link_to 'Catalog Index', catalogs_path, class: "btn btn-default", id: "" %>
	<%= link_to "Catalog Parse", {:controller => "toolbox", :action => "dashboard", :catalog_parse => true }, class: "btn btn-warning", id: "" %>
	<strong>Catalog Size:</strong> <%= @catalog_size %>
</p>
<p>
		<%= link_to 'Universe Index', universes_path, class: "btn btn-default" %>
		<%= link_to "Universe List Compile", {:controller => "toolbox", :action => "dashboard", :universe_update => true }, class: "btn btn-warning", id: "", data: { confirm: "Are you sure? this is going to take a bloody long time..." } %>
		<strong>Universe Size:</strong> <%= @universe_size %>
</p>
<%= link_to 'Flagged Entries', flagged_path, class: "btn btn-danger" %>
<%= link_to 'User Dashboard', user_dashboard_path, class: "btn btn-danger" %>
	<%= link_to "flag count reset", {:controller => "toolbox", :action => "dashboard", :flag_count_reset => true }, class: "btn btn-danger", id: "" %>

app/views/toolbox/flagged.html.erb
<h2>Flagged Entries</h2>

<% if @catalog.blank? == true %>
<%= will_paginate @catalogs %>

	<table>
	  <thead>
	    <tr>
	      <th>ID</th>
	      <th>User</th>
	      <th>Entry</th>
	      <th>System</th>
	      <th>System esi</th>
	      <th>Planet</th>
	      <th>Planet esi</th>
	      <th>Moon</th>
	      <th>Moon esi</th>
	      <th>Product</th>
	      <th>Product</th>
	      <th>Percent</th>
	      <th>Status</th>
	      <th>Verified</th>
	      <th>Flag</th>
	      <th></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @catalogs.each do |catalog| %>

			<% if @previous_entry != catalog.product_id && @previous_entry != nil %>
				<tr>
					<td colspan="20"></td>
				</tr>
			<% end %>

			<tr class='flagged_row'>
				<td><%= catalog.id %></td>
				<td><%= catalog.user_id %></td>
				<td><%= catalog.entry_id %></td>
				<td><%= catalog.system_id %></td>
				<td><%= catalog.system_esi %></td>
				<td><%= catalog.planet_id %></td>
				<td><%= catalog.planet_esi %></td>
				<td><%= catalog.moon_id %></td>
				<td><%= catalog.moon_esi %></td>
				<td><%= catalog.product_id %></td>
				<td><%= catalog.product %></td>
				<td><%= catalog.percent %></td>
				<td><%= catalog.status %></td>
				<td><%= catalog.verified %></td>
				<td><%= catalog.flag %></td>
				<td><%= link_to "Approve Entry", {:controller => "toolbox", :action => "flagged", :flagged_post => catalog.id }, class: "btn btn-warning", id: "" %>
				</td>
				<td><%= link_to 'Delete Entry', catalog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", id: "" %></td>

			</tr>


			<% @previous_entry = catalog.product_id %>

	    <% end %>
	  </tbody>
	</table>
<% else %>
<strong>No flagged entries.</strong>
<%= link_to 'Back', :back, class: "btn btn-default", id: "" %>
<% end %>

app/views/toolbox/info.html.erb
<% if @catalogs.empty? == false %>
<h2><%= @catalogs[0].moon_esi %></h2>


<div class='col-xs-7 col-sm-7 col-md-7'>
<table class='col-xs-12 col-sm-12 col-md-12' id='data_table'>
  <h3>Material Breakdown</h3>
  <thead>
    <tr>
      <th>Product</th>
      <th>Percent</th>
      <th>Estimated Value per unit</th>
      <th>Percent of cost</th>
      <th>Estimated Total per cycle</th>
    </tr>
  </thead>
  <tbody>
    <% @total=0 %>
    <% @mats_breakdown.each_with_index do |material, i| %>

    <tr class="<%= Toolbox.material_check(material.product) %> opacity-90 info_table">
      <td><%= material.product %></td>
      <td id="percent_<%= i %>" price_data="<%= @percent = material.percent.round(4)*100.to_f %>" ><%= @percent %> </td>
      <td id="product_price_<%= i %>" price_data="<%= @market = (Toolbox.EvE_Market(material.product_id).to_i)%>" ><%= number_with_delimiter(@market, :delimiter => ',') %> ISK</td>
      <% @total = @total + @market.to_i %>
      <td id="total_percent_<%= i %>">% of Cost</td>

      <td id="total_price_<%= i %>" class='value_cell'>*</td>
    </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td id='total_unit_value' class='hidden' price_data="<%= @total %>" ><%= number_with_delimiter(@total, :delimiter => ',') %> ISK</td>
      <td>
        <div id="slider">
          <div id="custom-handle" class="ui-slider-handle"></div>
        </div></td>
      <td id='total_value' class='value_cell'>Total Value</td>
    </tr>
  </tbody>
</table>
<div>
* These prices are based on the current game adjusted price of each item (the prices from that stock ticker on the market window).  This does not accuratly reflect the prices in Jita, Amarr, or any other market hub.  In addition this pricing is based on the raw materials found on the moon which are heavy and in most cases processed on site.  
</div>
<table>
  <tr>
  <th>Reprocess Material</th>
  </tr><tr>
  <% @repro_breakdown.each_with_index do |data, i| %>
    <td class='repro_breakdown' ><%= data.to_s %></td>
    <% if (i+1) % 8 == 0 %>
    </tr><tr>
    <% end %>
  
  <% end %>
</table>
* This does not include normal rocks, it only includes moon rocks and residual minerals.
</div>

<% @mats_breakdown.each do |material| %>
<% @chart_array[0].push(material.product) %>
<% @chart_array[1].push((material.percent.round(4)*100).to_f) %>
<% @chart_array[2].push(Toolbox.material_color_check(material.product)) %>
<% end %>
<% Rails.logger.info "Chart Array: " + @chart_array[0].inspect.html_safe %>

<canvas id="pie-chart" width="450" height="350"></canvas>
<script>
  new Chart(document.getElementById("pie-chart"), {
    type: 'pie',
    data: {
      labels: <%= @chart_array[0].inspect.html_safe %>,
      datasets: [{
        backgroundColor: <%= @chart_array[2].inspect.html_safe %>,
        data: <%= @chart_array[1].inspect.html_safe %>, 
      }]
    },
    options: {
      cutoutPercentage: 50,

      tooltips: {
        bodyFontSize: 64
      }, 
      legend: {
        display: true,
        position: 'left',
        labels: {
          fontSize: 48
        }
      }
    }
  });
</script>

<% if current_user.admin == true %>
  <div class="card-header" role="tab">
    <h5 class="mb-0">
      <div class="collapsed btn btn-default" data-toggle="collapse" href="#collapse" aria-expanded="false" aria-controls="collapse">
        Admin Data
      </h5>
      <div id="collapse" class="collapse row" role="tabpanel" aria-labelledby="heading" data-parent="#accordion">
        <div class="card-body">
          <table>
            <h3>All Entries for <%= @catalogs[0].moon_esi %> (<%= @catalogs[0].moon_id %>)</h3>
            <thead>
              <tr>
                <th>ID</th>
                <th>System</th>
                <th>Product ID</th>
                <th>Product</th>
                <th>Percent</th>
                <th>Status</th>
                <th>Flag</th>
                <th colspan="2"></th>
              </tr>
            </thead>

            <tbody>
              <% @catalogs.each do |catalog| %>
              <tr>
                <td><%= catalog.id %></td>
                <td><%= catalog.system_esi %></td>
                <td><%= catalog.product_id %></td>
                <td><%= catalog.product %></td>
                <td><%= catalog.percent %></td>
                <td><%= catalog.status %></td>
                <td><%= catalog.flag %></td>
                <% if current_user.admin == true %>
                <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
                <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>


      </div>
    </div>
  <% end %>

  <% end %>

app/views/toolbox/landing.html.erb
<h1>VRTEX Moon Registry</h1>

<div class='well'>Find systems by searching in the <%= link_to 'Catalog', regions_path, class: "btn btn-default" %> or search for system names (must be exact) or by moon ID number.</div>

<h2>Instructions for data entry</h2>
<ol>
	<li>1) Create a login / Sign in.</li>
	<li>2) Go to the <%= link_to '"New Entry"', new_entry_path %> Page.</li>
	<li>3) Use the new in-game "Copy to Clipboard" feature in the moon scanner, copy the data into the text area and submit.</li>
	<li>4) ???</li>
	<li>5) Profit!!!</li>
</ol>

app/views/toolbox/systems.html.erb
<table>
<tr class="row">
<% @systems.each_with_index do |i, index| %>
<th class="well col-md-2">
	<% if i.content == true %>
		<%= link_to i.system_name.to_s, {:controller => "toolbox", :action => "search", :search => i.system_name.to_s }, class: "", id: "" %>
	<% else %>
		<%= link_to i.system_name.to_s, {:controller => "toolbox", :action => "search", :search => i.system_name.to_s }, class: "inactive", id: "" %>
	<% end %>
	<% if 0 == (index+1) % 6 %>
	</tr><tr class="row">
	<% end %>
</th>
<% end %>
</tr>
</table>