config/routes.rb
Rails.application.routes.draw do
  resources :universes
  resources :catalogs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :moons
  resources :entries
  root 'toolbox#landing'
  resources :users
  resources :moons
  get '/dashboard' => 'toolbox#dashboard'
  get '/user_index' => 'toolbox#user_index'
  get '/search' => 'toolbox#search'
  get '/regions' => 'toolbox#regions'
  get '/systems' => 'toolbox#systems'
  get '/user_catalog' => 'toolbox#user_catalog'
  get '/user_dashboard' => 'toolbox#user_dashboard'

  get '/flagged' => 'toolbox#flagged'
  get '/info' => 'toolbox#info'

  get '/' => 'toolbox#landing'



end

app/models/moon.rb
class Moon < ActiveRecord::Base
	belongs_to :catalog


	def self.Moon_Parse
		Rails.logger.info 'Moon Check'
		@moons = Moon.where('validation' => nil)
		@moons.each do |moon|
			begin
			valid = true
			Rails.logger.info "========================================"

			# Rails.logger.info moon.entry_id.to_s + " | " +  moon.product.to_s
			esi_product = Toolbox.EvE_Request("https://esi.tech.ccp.is/latest/universe/types/id/?datasource=singularity&language=en-us", moon.ore_type_id.to_s)["name"]
			esi_system = Toolbox.EvE_Request("https://esi.tech.ccp.is/latest/universe/systems/id/?datasource=singularity&language=en-us", moon.system_id.to_s)["name"]
			esi_planet = Toolbox.EvE_Request("https://esi.tech.ccp.is/latest/universe/planets/id/?datasource=singularity", moon.planet_id.to_s)["name"]
			esi_moon = Toolbox.EvE_Request("https://esi.tech.ccp.is/latest/universe/moons/id/?datasource=singularity", moon.moon_id.to_s)["name"]
			
			if esi_product != moon.product
				valid = false
			end	

			if 	esi_moon.to_s.split(/ /)[0] != esi_planet.to_s.split(/ /)[0] || esi_moon.to_s.split(/ /)[0] != esi_system.to_s.split(/ /)[0] || esi_planet.to_s.split(/ /)[0] != esi_system.to_s.split(/ /)[0]
				valid = false
			end

			Rails.logger.info esi_moon.to_s.split(/ /)[0] + " | " + esi_planet.to_s.split(/ /)[0] + " | " + esi_system.to_s.split(/ /)[0]
			Rails.logger.info esi_product.to_s + " | " + moon.product.to_s + " | " + moon.quantity.to_s
			Rails.logger.info "Catalog green light: " + valid.to_s

			if valid == true
				moon.update(validation: true)
				Rails.logger.info "Create Catalog Entry for " + moon.id.to_s + " | " + valid.to_s
				catalog_entry = Catalog.new do |u|
					u.entry_id = moon.entry_id.to_i
					u.user_id = moon.user_id.to_i
					u.system_id = moon.system_id.to_i
					u.system_esi =  esi_system
					u.planet_id = moon.planet_id.to_i
					u.planet_esi = esi_planet
					u.moon_id = moon.moon_id.to_i
					u.moon_esi = esi_moon
					u.product_id = moon.ore_type_id.to_i
					u.product = esi_product
					u.percent = moon.quantity
					# Universe.universe_update(moon.system_id.to_i)
				end
				catalog_entry.save

			else
				# Rails.logger.info "Flag Counter: " + moon.user_id.to_s

				moon.update(validation: false)
				# user = User.find(moon.user_id.to_i)
				# total_flags = user.flags + 1
				# # user.update(flags: total_flags)
			end
 			rescue
				Rails.logger.info "Moon Parse Error for " + moon.id.to_s
			end
		end
	end
end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController
  before_action :set_moon, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_action :admin_check

  # GET /moons
  # GET /moons.json
  def index
    @moons = Moon.all.paginate(:page => params[:page], :per_page => 75).order(id: :desc)
  end

  # GET /moons/1
  # GET /moons/1.json
  def show
  end

  # GET /moons/new
  def new
    @moon = Moon.new
  end

  # GET /moons/1/edit
  def edit
  end

  # POST /moons
  # POST /moons.json
  def create
    @moon = Moon.new(moon_params)

    respond_to do |format|
      if @moon.save
        format.html { redirect_to @moon, notice: 'Moon was successfully created.' }
        format.json { render :show, status: :created, location: @moon }
      else
        format.html { render :new }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moons/1
  # PATCH/PUT /moons/1.json
  def update
    respond_to do |format|
      if @moon.update(moon_params)
        format.html { redirect_to @moon, notice: 'Moon was successfully updated.' }
        format.json { render :show, status: :ok, location: @moon }
      else
        format.html { render :edit }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moons/1
  # DELETE /moons/1.json
  def destroy
    @moon.destroy
    respond_to do |format|
      format.html { redirect_to moons_url, notice: 'Moon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moon
      @moon = Moon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moon_params
      params.require(:moon).permit(:entry_id, :product, :quantity, :ore_type_id, :system_id, :planet_id, :moon_id)
    end
end

app/helpers/moons_helper.rb
module MoonsHelper
end

app/views/moons/_form.html.erb
<%= form_for(@moon) do |f| %>
  <% if @moon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moon.errors.count, "error") %> prohibited this moon from being saved:</h2>

      <ul>
      <% @moon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :ore_type_id %><br>
    <%= f.number_field :ore_type_id %>
  </div>
  <div class="field">
    <%= f.label :system_id %><br>
    <%= f.number_field :system_id %>
  </div>
  <div class="field">
    <%= f.label :planet_id %><br>
    <%= f.number_field :planet_id %>
  </div>
  <div class="field">
    <%= f.label :moon_id %><br>
    <%= f.number_field :moon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moons/edit.html.erb
<h1>Editing Moon</h1>

<%= render 'form' %>

<%= link_to 'Show', @moon %> |
<%= link_to 'Back', moons_path %>

app/views/moons/index.html.erb
<h1>Moons Index (step 2)</h1>
<%= will_paginate @moons, class: "float-left" %>

<table>
  <thead>
    <tr>
      <th>Entry ID</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Ore type</th>
      <th>System</th>
      <th>Planet</th>
      <th>Moon</th>
      <th>Validation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moons.each do |moon| %>
      <tr>
        <td><%= moon.entry_id %></td>
        <td><%= moon.product %> </td>
        <td><%= moon.quantity %> | </td>
        <td><%= moon.ore_type_id %> | </td>
        <td><%= moon.system_id %> | </td>
        <td><%= moon.planet_id %> | </td>
        <td><%= moon.moon_id %> | </td>
        <td><%= moon.validation %></td>
        <td><%= link_to 'Show', moon %></td>
        <td><%= link_to 'Edit', edit_moon_path(moon) %></td>
        <td><%= link_to 'Destroy', moon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moon', new_moon_path %>

app/views/moons/new.html.erb
<h1>New Moon</h1>

<%= render 'form' %>

<%= link_to 'Back', moons_path %>

app/views/moons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Product:</strong>
  <%= @moon.entry_id %>
</p>
<p>
  <strong>Product:</strong>
  <%= @moon.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @moon.quantity %>
</p>

<p>
  <strong>Ore type:</strong>
  <%= @moon.ore_type_id %>
</p>

<p>
  <strong>System:</strong>
  <%= @moon.system_id %>
</p>

<p>
  <strong>Planet:</strong>
  <%= @moon.planet_id %>
</p>

<p>
  <strong>Moon:</strong>
  <%= @moon.moon_id %>
</p>

<%= link_to 'Edit', edit_moon_path(@moon) %> |
<%= link_to 'Back', moons_path %>