config/routes.rb
Rails.application.routes.draw do
  resources :universes
  resources :catalogs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :moons
  resources :entries
  root 'toolbox#landing'
  resources :users
  resources :moons
  get '/dashboard' => 'toolbox#dashboard'
  get '/user_index' => 'toolbox#user_index'
  get '/search' => 'toolbox#search'
  get '/regions' => 'toolbox#regions'
  get '/systems' => 'toolbox#systems'
  get '/user_catalog' => 'toolbox#user_catalog'
  get '/user_dashboard' => 'toolbox#user_dashboard'

  get '/flagged' => 'toolbox#flagged'
  get '/info' => 'toolbox#info'

  get '/' => 'toolbox#landing'



end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%= link_to root_path, class: "navbar-brand", 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' do  %>
          VRTEX Moon Registry<span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Home', '/' %></li>
            <% if current_user.blank? == false %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Catalog', regions_path %></li>
            <li>
              <div class="input-group">
                <%= form_tag(search_path, :method => "get", id: "search-form", class: 'input-group') do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search ", :class => 'form-control', :id => 'search-area', :type => 'text', aria:{describedby: 'basic-addon2'} %>
                <%= button_tag(:name => nil, class: 'input-group-addon', id: 'basic-addon2') do %>
                <span>Search</span>
                <% end %>
                <% end %>
              </div>
            </li>

            <li><%= link_to 'New Entry', new_entry_path %></li>
            <% if current_user.blank? == false %>
            <li><%= link_to 'My Catalog', user_catalog_path %></li>
            <% end %>
            <% if current_user.blank? == false %>
            <% if current_user.admin == true %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Dashboard', dashboard_path %></li>

            <% end %>
            <% end %>
            <% end %>
          </ul>
        </li>
      </ul>
      <div class="login">
        <% if user_signed_in? %>
        <li>
          Signed in as <%= current_user.email %>
        </li>
        <li>
          <%= link_to('Edit Account', edit_user_registration_path) %> | <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> | <%= current_user.id %>
          <% if current_user.admin == true %>
          Admin
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <li>
          <%= link_to('Sign Up', new_user_registration_path)  %>
        </li>
        <% end %>
      </div>
      <div class="notice">
        <p id="notice"><%= notice %></p>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>VRTEX Moon Registry</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>

	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<%= render :partial => 'layouts/navbar' %>


</head>
<body>
	<div class='container-fluid'>
		<%= yield %>
	</div>
</body>
</html>